id: P76D9B9D2
initial_creation_type: input
source_metadata:
  title: Pemakö Series
  language: en
  description: 'Texts related to the hidden land of Pemakö (pad+ma bkod), or Pemokö
    (pad+mo bkod), famed as a sanctuary from warfare and disease:'
  volume:
    8ab5937ce6cd47d9bd127ff3917c64fd:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Aspiration Prayers
    9e52f3ecf63d499b93b5778ce23e7c17:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Guides
created_at: '2022-03-01T05:04:10.101136'
last_modified_at: '2022-03-01T05:04:10.101141'
